### ISSUE TITLE
can't add new "action section" to default page

### ISSUE THREAD

**Issue by rileydog** [collective/collective.contentsections#10]
When a page is assigned as "default page", the "add" action does not support adding another action section on the page. Instead it is the standard Plone "add" options of page, event, file, etc.

==================================================

1) i know there is the "add item to default page" in the "Add" button; however, that doesn't do anything.
2) trying to add directly to the page from the "Add" does not give the option of adding an "action section" 

work around.
- while viewing page where you want to add an action, click on "contents"
- change the 'default' page to another page
- go back to page and now you can make additions
- when done, go back and make the page the default again.

**Comment by rileydog** [comment]
Hello, i have tried this product and find it very useful because of the design choices you made to keep it simple.  I would like to use it on a production site; however, with this bug it makes it challenging to use.
     would you be able to confirm if this is a bug?   also, would you be willing to either:  fix the bug, give me an estimated cost to fix it or, point to the general section of the product where i can direct my programmer to look to fix this issue.
    thanks for any help you can give.

**Comment by sverbois** [comment]
Hello. Sorry for my late reply. It is indeed a very annoying bug.
I'm going on vacation this week but I'll try to look at it after August 20.

**Comment by rileydog** [comment]
thanks a lot.  have a good vacation.

**Comment by sverbois** [comment]
I found the bug in Plone.
See https://github.com/plone/plone.app.contentmenu/pull/55
I'm thinking of adding a temporary workaround this weekend in collective.contentsections while waiting for a fixed version of plone.app.contentmenu.
