### ISSUE TITLE
Error creating a Selection Section

### ISSUE THREAD

**Issue by rileydog** [collective/collective.contentsections#9]
**What I did**

Tried to create a "Selection Section" on a page.    (Note: i tested all other setions and they work as advertised.

**What Happened**

Got this error

Here is the full error message:

T**raceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 181, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 390, in publish_module
  Module ZPublisher.WSGIPublisher, line 285, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module plone.z3cform.layout, line 63, in __call__
  Module plone.z3cform.layout, line 47, in update
  Module plone.dexterity.browser.add, line 137, in update
  Module plone.z3cform.fieldsets.extensible, line 65, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 301, in __call__
  Module z3c.form.button, line 159, in __call__
  Module plone.dexterity.browser.add, line 115, in handleAdd
  Module z3c.form.form, line 263, in createAndAdd
  Module plone.dexterity.browser.add, line 81, in create
  Module plone.dexterity.browser.add, line 197, in _applyChanges
  Module plone.app.relationfield.widget, line 141, in set
  Module five.intid.intid, line 44, in getId
  Module zope.intid, line 108, in getId
zope.intid.interfaces.IntIdMissingError: <PloneSite at /junk>
============**

**Comment by sverbois** [comment]
What version of Plone/Python are you using?
I have no problem with Plone 6.0.0 / Python 3.9.15.

**Comment by rileydog** [comment]
Plone 6.0.2 (6013)
    CMF 2.7.0
    Zope 5.8
    Python 3.11.2 (main, Mar 1 2023, 14:56:17) [GCC 10.2.1 20210110]
    PIL 9.4.0 (Pillow)
    WSGI: On
    Server: waitress 2.1.2

**Comment by rileydog** [comment]
Today, i got a differnt (I'm good at creating errors)  :(
=================================
(Note:  this is about a missing vocabulary for taxonomy.  The only thing I can think of that I did that might cause the issue is, after installation, I saw the taxonomy product installed and i uninstalled.  After reading your page more closely I realized I needed it and re-installed.


Actions I took

1) installed collective.contentsections.
2) the contentsections and 'collective.taxonomy both installed
3) created new page.  went fine.
4) tried to add section.  Got this error: 

We’re sorry, but there seems to be an error…

Here is the full error message:

Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 181, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 390, in publish_module
  Module ZPublisher.WSGIPublisher, line 285, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module plone.z3cform.layout, line 63, in __call__
  Module plone.z3cform.layout, line 47, in update
  Module plone.dexterity.browser.add, line 137, in update
  Module plone.z3cform.fieldsets.extensible, line 65, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 141, in update
  Module z3c.form.group, line 52, in update
  Module z3c.form.group, line 48, in updateWidgets
  Module z3c.form.field, line 274, in update
  Module z3c.form.browser.select, line 51, in update
  Module z3c.form.browser.widget, line 171, in update
  Module z3c.form.widget, line 233, in update
  Module z3c.form.widget, line 225, in updateTerms
  Module zope.component._api, line 102, in getMultiAdapter
  Module zope.component._api, line 116, in queryMultiAdapter
  Module zope.interface.registry, line 364, in queryMultiAdapter
  Module zope.interface.adapter, line 844, in queryMultiAdapter
  Module z3c.form.term, line 248, in CollectionTerms
  Module zope.schema._field, line 471, in bind
  Module zope.schema._field, line 455, in _resolve_vocabulary
zope.schema._field.MissingVocabularyError: Can't validate value without vocabulary named 'collective.taxonomy.section_css_classes'

**Comment by rileydog** [comment]
sorry to overload you; however, I'm trying to give you any info that might be relevant.  
=====================

**Intro**

I had some issues with the product and tried a workaround.  Not sure if this is my problem.  I took the workaround because if i didn't when i installed your product, i couldn't uninstall it without causing issues and the original Plone Page, was no longer available
==========================

**Information**

For both News and Events, the content type is not listed to be added when on the respective folders, as it should be.  

I can choose the ‘more’ option for Event and choose event from the list;however,this isn't useful for someone not familiar with Plone

Also, News can’t be added at all – not on any list.   Note:  "News" dex type doesn’ export properly, it doesn’t have the “Types Folder”  only the “Types.xml”  	
=====================================

**MY WORK AROUND**

At Content Type section of site:

Export “Event” .   Note:  News doesn’t’ export properly, it doesn’t have the “Types Folder”  only the “Types.xml”.  thus, importing back in doesn’t work.
Delete Event
Delete News
Delete Page
Add “collective.contentsections”
Activate it 
At CT, delete the “Event” added   (News doesn’t get added by product)  Also
Upload the Event CT exported above.
Recreate News

**Comment by rileydog** [comment]
Ok, I know what the issue is.  

I did a lengthy workaround because of two issues:  1) the standard Plone page was no longer available in case I wanted to revert back to it; 2) the Event and News content types don't act as they should.  The News CT is not addable at all  and the Event can only be added by going to additional options (forget the term) after selecting "Add New" and no content type shown.

Do you have idea on how I can fix this?

The only issue to me is the News and Events not working as expected.  As I stated before the product is very good for what it desinged for - thanks

**Comment by sverbois** [comment]
The collective.contentsection product disables the standard Plone types "Page", "News" and "Event" and adds two new content types "Page" and "Event". I should rename them "Standard Page" and "Event Page". The collective.contentsection product is not supposed to be used with the standard Plone "Page", "News" and "Event" content and is not supposed to be uninstalled once it has been used. I will however improve the uninstall profile and add a "News Page" content type.

**Comment by sverbois** [comment]
I can't reproduce your problem with these versions
```
Plone 6.0.2 (6013)
CMF 2.7.0
Zope 5.8
Python 3.11.2 (main, Mar 1 2023, 14:56:17) [GCC 10.2.1 20210110]
PIL 9.4.0 (Pillow)
WSGI: On
Server: waitress 2.1.2
```

**Comment by rileydog** [comment]
Thanks for responding, I apologize for the confusion and causing extra work for you.  
     
The "bug" was caused by me trying to force your product to do something it wasn't intended to.
 
Your description of what the product does (including the pictures of the new sections etc.) was excellent.

Perhaps you just give a quick explanation as  you did above and add the "This product can't be uninsstalled" that some products have.

**Comment by rileydog** [comment]
This was my misunderstanding of the product.  no change required.
